# Generated by Django 5.0.7 on 2024-09-15 08:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='cards/')),
                ('image2', models.ImageField(upload_to='cards/')),
                ('image3', models.ImageField(upload_to='cards/')),
                ('image4', models.ImageField(upload_to='cards/')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=300)),
                ('artikul', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=50)),
                ('spare_part_number', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=50)),
                ('choice', models.CharField(choices=[('Новый', 'Новый'), ('Б/У', 'БУ')], default='Новый', max_length=6)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.category')),
            ],
        ),
    ]
