# Generated by Django 5.0.7 on 2024-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('NEW', 'Новый'), ('USED', 'БУ')], default='NEW', max_length=4),
        ),
    ]
