# Generated by Django 5.0.7 on 2024-08-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_product_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Б/У', 'БУ')], default='Новый', max_length=6),
        ),
    ]
